services:

  postgres:
    image: postgres:16-alpine
    shm_size: "512mb"
    container_name: pingxy-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pingxy-network
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: pingxy-migration
    restart: no
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    networks:
      - pingxy-network
    depends_on:
      postgres:
        condition: service_healthy
    command: [ "bun", "run", "db:migrate" ]

  redis:
    image: redis:7-alpine
    container_name: pingxy-redis
    networks:
      - pingxy-network
    restart: always
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: pingxy-backend
    restart: always
    depends_on:
      migration:
        condition: service_completed_successfully
      storage:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - PORT=3000
      - SERVER_ID=${HOSTNAME}
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ENDPOINT=http://storage:9000
      - MINIO_BUCKET=pingxy
      - S3_REGION=us-east-1
      - REDIS_URL=redis://redis:6379

    networks:
      - pingxy-network
    command: [ "bun", "run", "start" ]

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: pingxy-frontend
    restart: always
    environment:
      - PORT=5173
      - ORIGIN=https://pingxy.com
      - CHECK_ORIGIN=true
      - INTERNAL_BACKEND_URL=http://backend:3000
    networks:
      - pingxy-network
    command: [ "bun", "run", "start" ]

  storage:
    image: minio/minio
    container_name: pingxy-storage
    restart: always
    networks:
      - pingxy-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  caddy:
    image: caddy:alpine
    container_name: pingxy-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pingxy-network
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

networks:
  pingxy-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  redis_data:
  caddy_data:
  caddy_config: