services:
  db:
    image: postgres:16-alpine
    container_name: chat-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password123}
      POSTGRES_DB: ${DB_NAME:-chat_app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-chat_app}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: chat-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${DB_USER:-admin}:${DB_PASSWORD:-password123}@db:5432/${DB_NAME:-chat_app}

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: chat-frontend-builder
    volumes:
      - frontend_dist:/app/frontend/dist

  nginx:
    image: nginx:alpine
    container_name: chat-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginxprod.conf:/etc/nginx/nginx.conf:ro # Using your nginxprod.conf
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      frontend:
        condition: service_completed_successfully
      backend:
        condition: service_started

volumes:
  frontend_dist:
  postgres_data:
