export const testUsers = [
  {
    uid: "test1",
    username: "test1",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test2",
    username: "test2",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test3",
    username: "test3",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test4",
    username: "test4",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test5",
    username: "test5",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test6",
    username: "test6",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test7",
    username: "test7",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test8",
    username: "test8",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test9",
    username: "test9",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test10",
    username: "test10",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test11",
    username: "test11",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test12",
    username: "test12",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test13",
    username: "test13",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test14",
    username: "test14",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test15",
    username: "test15",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test16",
    username: "test16",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test17",
    username: "test17",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test18",
    username: "test18",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test19",
    username: "test19",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test20",
    username: "test20",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test21",
    username: "test21",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test22",
    username: "test22",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test23",
    username: "test23",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test24",
    username: "test24",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test25",
    username: "test25",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test26",
    username: "test26",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test27",
    username: "test27",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test28",
    username: "test28",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test29",
    username: "test29",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test30",
    username: "test30",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test31",
    username: "test31",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test32",
    username: "test32",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test33",
    username: "test33",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test34",
    username: "test34",
    age: "0",
    gender: "0",
    country: "0",
  },
  {
    uid: "test35",
    username: "test35",
    age: "0",
    gender: "0",
    country: "0",
  },
];
