import { Hono } from "hono";
import { deleteCookie, setCookie } from "hono/cookie";
import { sign } from "hono/jwt";
import type { User } from "../../../shared/src/lib/utils/validation";
import { userSockets, announcedUsers } from "../state";
import { createUser, deleteUser, getUserByUsername, getUser, getUserWithAuth } from "../db";

const app = new Hono();

app.post("/register", async (c) => {
    const body = await c.req.json();
    const { username, password, user } = body;

    if (!username || !password || !user) {
        return c.json({ error: "Missing required fields" }, 400);
    }

    const existing = getUserByUsername(username);
    if (existing) {
        return c.json({ error: "Username taken" }, 409);
    }

    const passhash = await Bun.password.hash(password);

    // Ensure the user object has the username and uid (if valid)
    // We should probably trust the UID generated by frontend or generate one here.
    // For now, assume frontend sends a valid User object.

    const success = createUser(
        { ...user, username }, // ensure username matches
        passhash,
        false // not a guest
    );

    if (!success) {
        return c.json({ error: "Failed to create user" }, 500);
    }

    // Auto-login after register
    const payload = { user: { ...user, username } };
    const secret = process.env.JWT_SECRET || "fallback_secret_for_dev";
    const token = await sign(payload, secret);

    setCookie(c, "sessionid", token, {
        maxAge: 60 * 60 * 24 * 7,
        httpOnly: false,
        secure: false, // Set true in production
        path: "/",
        sameSite: "lax",
    });

    return c.json({
        uid: user.uid,
        username: username,
        token: token,
    });
});

app.post("/login", async (c) => {
    const body = await c.req.json();
    const { username, password } = body;

    if (!username || !password) {
        return c.json({ error: "Missing credentials" }, 400);
    }

    const record = getUserWithAuth(username);
    if (!record) {
        return c.json({ error: "Invalid credentials" }, 401);
    }

    const { user, passhash } = record;

    if (!passhash) {
        return c.json({ error: "Account requires setup or is guest" }, 401);
    }

    const match = await Bun.password.verify(password, passhash);
    if (!match) {
        return c.json({ error: "Invalid credentials" }, 401);
    }

    const payload = { user };
    const secret = process.env.JWT_SECRET || "fallback_secret_for_dev";
    const token = await sign(payload, secret);

    setCookie(c, "sessionid", token, {
        maxAge: 60 * 60 * 24 * 7,
        httpOnly: false,
        secure: false,
        path: "/",
        sameSite: "lax",
    });

    return c.json({
        uid: user.uid,
        username: user.username,
        token: token,
    });
});

app.post("/guest", async (c) => {
    const body = await c.req.json();
    const { user } = body; // User object from frontend

    if (!user) {
        return c.json({ error: "Missing user data" }, 400);
    }

    // Guest login: Just create/update user without password
    // Check if username taken by a REGISTERED user?
    const existing = getUserWithAuth(user.username);
    if (existing && existing.passhash) {
        return c.json({ error: "Username taken by registered user" }, 409);
    }

    // If existing guest, or new, we upsert.
    // Our createUser is insert-only, need to check collision by UID or Username.

    // Simplification: Try create. If username collision, fail.
    // Ideally guest usernames should be unique or appended with #1234.
    // Existing frontend logic handles unique IDs/Usernames roughly.

    if (!existing) {
        const success = createUser(user, null, true);
        if (!success) return c.json({ error: "Failed to create guest" }, 500);
    } else {
        // If guest exists (no passhash), we just log them in? 
        // Or if they are trying to start FRESH with same username, we might fail if UID differs.
        // Let's assume re-login for guest is fine if they have the keys, but this endpoint is usually for NEW sessions.
        // We do nothing if exists, just issue token.
    }

    // Re-fetch user to get stored data (if we want to be safe) or use passed data
    // existing might rely on stored data.

    const payload = { user };
    const secret = process.env.JWT_SECRET || "fallback_secret_for_dev";
    const token = await sign(payload, secret);

    setCookie(c, "sessionid", token, {
        maxAge: 60 * 60 * 24 * 7,
        httpOnly: false,
        secure: false,
        path: "/",
        sameSite: "lax",
    });

    return c.json({
        uid: user.uid,
        username: user.username,
        token: token,
    });
});

app.post("/logout", (c) => {
    const user: User = c.get("jwtPayload")?.user;

    if (user) {
        const uid = user.uid;
        announcedUsers.delete(uid);
        const userSocket = userSockets.get(uid);
        if (userSocket) {
            userSocket.close();
        }
        userSockets.delete(uid);
    }

    deleteCookie(c, "sessionid", {
        maxAge: 0,
        httpOnly: false,
        path: "/",
        secure: false,
        sameSite: "lax",
    });

    return c.json({ message: "logged out" });
});

export default app;
