import { Hono } from "hono";
import { deleteCookie, setCookie } from "hono/cookie";
import { sign } from "hono/jwt";
// import type { User } from "../../../shared/src/lib/utils/validation";
// import { userSockets, announcedUsers } from "../state";
// import {
//   createUser,
//   deleteUser,
//   getUserByUsername,
//   getUser,
//   getUserWithAuth,
// } from "../db/users";
// import { createSession, deleteSession } from "../db/sessions";
// import { authMiddleware } from "../middlewares/auth";
import { getConnInfo } from "hono/bun";

import * as db from '../db/index.js'
import { User, NewUser } from "../db/schema/_schema.js";


const app = new Hono();

// function getJwtSecret(): string {
//   const fromEnv = process.env.JWT_SECRET;
//   const isProd = process.env.NODE_ENV === "production";
//   if (fromEnv) return fromEnv;
//   if (!isProd) return "fallback_secret_for_dev";
//   throw new Error("JWT_SECRET is not configured in production environment");
// }

// const isProd = process.env.NODE_ENV === "production";

// //  TODO: include email
// app.post("/register", async (c) => {
//   const body = await c.req.json();
//   const { username, password, user } = body;

//   if (!username || !password || !user) {
//     return c.json({ error: "Missing required fields" }, 400);
//   }

//   const existing = getUserByUsername(username);
//   if (existing) {
//     return c.json({ error: "Username taken" }, 409);
//   }

//   const hashed_password = await Bun.password.hash(password);

//   // Ensure the user object has the username and uid (if valid)
//   // We should probably trust the UID generated by frontend or generate one here.
//   // For now, assume frontend sends a valid User object.
//   user.roles = ["user"];
//   const success = createUser(
//     { ...user, username }, // ensure username matches
//     hashed_password
//   );

//   if (!success) {
//     return c.json({ error: "Failed to create user" }, 500);
//   }

//   // Auto-login after register
//   // Create session and add it to payload
//   const info = getConnInfo(c);
//   const ip_address = info.remote.address!;
//   // Only minimal refresh of user object with ID
//   const newUser = getUser(user.uid) || { ...user, username };
//   const sid = createSession({ user: newUser, ip_address });
//   const payload = { uid: user.uid, sid };
//   const secret = getJwtSecret();
//   const token = await sign(payload, secret);

//   setCookie(c, "sessionid", token, {
//     maxAge: 60 * 60 * 24 * 7,
//     httpOnly: true,
//     secure: isProd,
//     path: "/",
//     sameSite: "lax",
//   });

//   return c.json({
//     uid: user.uid,
//     username: username,
//     token: token,
//   });
// });

// // LOGIN
// app.post("/login", async (c) => {
//   const body = await c.req.json();
//   const { username, password } = body;

//   if (!username || !password) {
//     return c.json({ error: "Missing credentials" }, 400);
//   }

//   const record = getUserWithAuth(username);
//   if (!record) {
//     return c.json({ error: "Invalid credentials" }, 401);
//   }

//   const { user, hashed_password } = record;

//   if (!hashed_password) {
//     return c.json({ error: "Account requires setup or is guest" }, 401);
//   }

//   const match = await Bun.password.verify(password, hashed_password);
//   if (!match) {
//     return c.json({ error: "Invalid credentials" }, 401);
//   }

//   //  Generate session id
//   //  Add it to paylod
//   const ip_address = getConnInfo(c).remote.address!;
//   const sid = createSession({ user, ip_address });
//   const payload = { uid: user.uid, sid };
//   const secret = getJwtSecret();
//   const token = await sign(payload, secret);

//   setCookie(c, "sessionid", token, {
//     maxAge: 60 * 60 * 24 * 7,
//     httpOnly: true,
//     secure: isProd,
//     path: "/",
//     sameSite: "lax",
//   });

//   // TODO: check if this is needed
//   c.set("jwtPayload", { user, sid });

//   return c.json({
//     uid: user.uid,
//     username: user.username,
//     token: token,
//   });
// });

// app.post("/guest", async (c) => {
//   const body = await c.req.json();
//   const { user } = body; // User object from frontend

//   if (!user) {
//     return c.json({ error: "Missing user data" }, 400);
//   }

//   // Guest login: Just create/update user without password
//   // Check if username taken by a REGISTERED user?
//   const existing = getUserWithAuth(user.username);
//   if (existing && existing.hashed_password) {
//     return c.json({ error: "Username taken by registered user" }, 409);
//   }

//   if (!existing) {
//     // Force guest role in object before creation to be safe,
//     // though createUser handles it via is_guest flag logic too.
//     user.roles = ["guest"];
//     const success = createUser(user, null);
//     if (!success) return c.json({ error: "Failed to create guest" }, 500);
//   }

//   // Re-fetch user to get stored data (permissions, etc)
//   const guestUser = getUser(user.uid) || user;

//   const ip_address = getConnInfo(c).remote.address!;
//   const sid = createSession({ user: guestUser, ip_address });
//   const payload = { uid: guestUser.uid, sid };
//   const secret = getJwtSecret();
//   const token = await sign(payload, secret);

//   setCookie(c, "sessionid", token, {
//     maxAge: 60 * 60 * 24 * 7,
//     httpOnly: true,
//     secure: isProd,
//     path: "/",
//     sameSite: "lax",
//   });

//   //  TODO: check what data to return after login
//   return c.json({
//     uid: guestUser.uid,
//     username: guestUser.username,
//     token: token,
//   });
// });

// app.post("/logout", authMiddleware, (c) => {
//   // We try to get the user from the context.
//   // If authMiddleware ran, it populated this.
//   // If not (e.g. invalid token), we just proceed to clear cookie.

//   const user: User = c.get("jwtPayload")?.user;
//   const sid: string = c.get("jwtPayload")?.sid;

//   if (user) {
//     const uid = user.uid;
//     announcedUsers.delete(uid);
//     const userSocket = userSockets.get(uid);
//     if (userSocket) {
//       userSocket.close();
//     }
//     userSockets.delete(uid);

//     // If guest, delete permanent record
//     // If not guest, keep permanent record
//     if (user.roles?.includes("guest")) {
//       deleteUser(uid);
//     }
//   }

//   // Delete Session
//   if (sid) {
//     deleteSession(sid);
//   }

//   // Delete cookie
//   deleteCookie(c, "sessionid", {
//     maxAge: 0,
//     httpOnly: true,
//     path: "/",
//     secure: isProd,
//     sameSite: "lax",
//   });

//   return c.json({ message: "logged out" });
// });





app.post("/register", async (c) => {
  const body = await c.req.json();

  // Check this if user is needed here!
  const { username, password, user } = body;

  if (!username || !password || !user) {
    return c.json({ error: "Missing required fields" }, 400);
  }

  const existingUser = await db.getUserByUsername(username);
  if (existingUser) {
    return c.json({ error: "Username taken" }, 409);
  }

  const hashed_password = await Bun.password.hash(password);

  const newUser: NewUser = {
    username: username,
    user_type: 'user' as const,
    hashed_password: hashed_password,
    data: { ...user },
  }

  const success = await db.createUser(newUser);
  if (!success) {
    return c.json({ error: "Failed to create user" }, 500);
  }

  // Auto login the user
  const info = getConnInfo(c);
  const ip_address = info.remote.address!;
  const [dbUser] = await db.getUserByUsername(username);
  const userAgent = c.req.header('User-Agent')!;
  if (!dbUser) {
    return c.json({ error: "User not found" }, 404);
  }
  const token = crypto.randomUUID();

  // Create session
  await db.createSession(
    token,
    dbUser.id,
    ip_address,
    userAgent
  );

  // Set cookie
  setCookie(c, "sessionid", token, {
    maxAge: 60 * 60 * 24 * 7,
    httpOnly: true,
    secure: false,
    path: "/",
    sameSite: "lax",
  });

  return c.json({
    uid: dbUser.id,
    username: dbUser.username,
    token: token,
  });

  // Only minimal refresh of user object with ID
  // const u = getUser(user.uid) || { ...user, username };
  // const sid = createSession({ user: u, ip_address });
  // const payload = { uid: u.uid, sid };
  // const secret = getJwtSecret();
  // const token = await sign(payload, secret);

  // setCookie(c, "sessionid", token, {
  //   maxAge: 60 * 60 * 24 * 7,
  //   httpOnly: true,
  //   secure: isProd,
  //   path: "/",
  //   sameSite: "lax",
  // });

  // // TODO: check if this is needed
  // c.set("jwtPayload", { user, sid });

  // return c.json({
  //   uid: user.uid,
  //   username: username,
  //   token: token,
  // });

})
export default app;
