import { Hono } from "hono";
import { deleteCookie, setCookie } from "hono/cookie";
import { sign } from "hono/jwt";
// import type { User } from "../../../shared/src/lib/utils/validation";
// import { userSockets, announcedUsers } from "../state";
// import {
//   createUser,
//   deleteUser,
//   getUserByUsername,
//   getUser,
//   getUserWithAuth,
// } from "../db/users";
// import { createSession, deleteSession } from "../db/sessions";
// import { authMiddleware } from "../middlewares/auth";
import { getConnInfo } from "hono/bun";
import { getCookie } from "hono/cookie";
import * as db from "../db/services/index.js";
import {
  User,
  NewUser,
  PublicUser,
} from "@chat/shared/src/lib/utils/validation";
import { authMiddleware } from "../middlewares/auth.js";
import { factory } from "../db/factory/index.js";

const app = factory.createApp();

// function getJwtSecret(): string {
//   const fromEnv = process.env.JWT_SECRET;
//   const isProd = process.env.NODE_ENV === "production";
//   if (fromEnv) return fromEnv;
//   if (!isProd) return "fallback_secret_for_dev";
//   throw new Error("JWT_SECRET is not configured in production environment");
// }

// const isProd = process.env.NODE_ENV === "production";

// //  TODO: include email
// app.post("/register", async (c) => {
//   const body = await c.req.json();
//   const { username, password, user } = body;

//   if (!username || !password || !user) {
//     return c.json({ error: "Missing required fields" }, 400);
//   }

//   const existing = getUserByUsername(username);
//   if (existing) {
//     return c.json({ error: "Username taken" }, 409);
//   }

//   const hashed_password = await Bun.password.hash(password);

//   // Ensure the user object has the username and uid (if valid)
//   // We should probably trust the UID generated by frontend or generate one here.
//   // For now, assume frontend sends a valid User object.
//   user.roles = ["user"];
//   const success = createUser(
//     { ...user, username }, // ensure username matches
//     hashed_password
//   );

//   if (!success) {
//     return c.json({ error: "Failed to create user" }, 500);
//   }

//   // Auto-login after register
//   // Create session and add it to payload
//   const info = getConnInfo(c);
//   const ip_address = info.remote.address!;
//   // Only minimal refresh of user object with ID
//   const newUser = getUser(user.uid) || { ...user, username };
//   const sid = createSession({ user: newUser, ip_address });
//   const payload = { uid: user.uid, sid };
//   const secret = getJwtSecret();
//   const token = await sign(payload, secret);

//   setCookie(c, "sessionid", token, {
//     maxAge: 60 * 60 * 24 * 7,
//     httpOnly: true,
//     secure: isProd,
//     path: "/",
//     sameSite: "lax",
//   });

//   return c.json({
//     uid: user.uid,
//     username: username,
//     token: token,
//   });
// });

// // LOGIN
// app.post("/login", async (c) => {
//   const body = await c.req.json();
//   const { username, password } = body;

//   if (!username || !password) {
//     return c.json({ error: "Missing credentials" }, 400);
//   }

//   const record = getUserWithAuth(username);
//   if (!record) {
//     return c.json({ error: "Invalid credentials" }, 401);
//   }

//   const { user, hashed_password } = record;

//   if (!hashed_password) {
//     return c.json({ error: "Account requires setup or is guest" }, 401);
//   }

//   const match = await Bun.password.verify(password, hashed_password);
//   if (!match) {
//     return c.json({ error: "Invalid credentials" }, 401);
//   }

//   //  Generate session id
//   //  Add it to paylod
//   const ip_address = getConnInfo(c).remote.address!;
//   const sid = createSession({ user, ip_address });
//   const payload = { uid: user.uid, sid };
//   const secret = getJwtSecret();
//   const token = await sign(payload, secret);

//   setCookie(c, "sessionid", token, {
//     maxAge: 60 * 60 * 24 * 7,
//     httpOnly: true,
//     secure: isProd,
//     path: "/",
//     sameSite: "lax",
//   });

//   // TODO: check if this is needed
//   c.set("jwtPayload", { user, sid });

//   return c.json({
//     uid: user.uid,
//     username: user.username,
//     token: token,
//   });
// });

// app.post("/guest", async (c) => {
//   const body = await c.req.json();
//   const { user } = body; // User object from frontend

//   if (!user) {
//     return c.json({ error: "Missing user data" }, 400);
//   }

//   // Guest login: Just create/update user without password
//   // Check if username taken by a REGISTERED user?
//   const existing = getUserWithAuth(user.username);
//   if (existing && existing.hashed_password) {
//     return c.json({ error: "Username taken by registered user" }, 409);
//   }

//   if (!existing) {
//     // Force guest role in object before creation to be safe,
//     // though createUser handles it via is_guest flag logic too.
//     user.roles = ["guest"];
//     const success = createUser(user, null);
//     if (!success) return c.json({ error: "Failed to create guest" }, 500);
//   }

//   // Re-fetch user to get stored data (permissions, etc)
//   const guestUser = getUser(user.uid) || user;

//   const ip_address = getConnInfo(c).remote.address!;
//   const sid = createSession({ user: guestUser, ip_address });
//   const payload = { uid: guestUser.uid, sid };
//   const secret = getJwtSecret();
//   const token = await sign(payload, secret);

//   setCookie(c, "sessionid", token, {
//     maxAge: 60 * 60 * 24 * 7,
//     httpOnly: true,
//     secure: isProd,
//     path: "/",
//     sameSite: "lax",
//   });

//   //  TODO: check what data to return after login
//   return c.json({
//     uid: guestUser.uid,
//     username: guestUser.username,
//     token: token,
//   });
// });

// app.post("/logout", authMiddleware, (c) => {
//   // We try to get the user from the context.
//   // If authMiddleware ran, it populated this.
//   // If not (e.g. invalid token), we just proceed to clear cookie.

//   const user: User = c.get("jwtPayload")?.user;
//   const sid: string = c.get("jwtPayload")?.sid;

//   if (user) {
//     const uid = user.uid;
//     announcedUsers.delete(uid);
//     const userSocket = userSockets.get(uid);
//     if (userSocket) {
//       userSocket.close();
//     }
//     userSockets.delete(uid);

//     // If guest, delete permanent record
//     // If not guest, keep permanent record
//     if (user.roles?.includes("guest")) {
//       deleteUser(uid);
//     }
//   }

//   // Delete Session
//   if (sid) {
//     deleteSession(sid);
//   }

//   // Delete cookie
//   deleteCookie(c, "sessionid", {
//     maxAge: 0,
//     httpOnly: true,
//     path: "/",
//     secure: isProd,
//     sameSite: "lax",
//   });

//   return c.json({ message: "logged out" });
// });

app.get("/verify", authMiddleware, async (c) => {
  return c.json({ message: "test" }, 200);
});



// Register route
app.post("/register", async (c) => {
  const body = await c.req.json();

  // Check this if user is needed here!
  const { username, password, user } = body;

  if (!username || !password || !user) {
    return c.json({ error: "Missing required fields" }, 400);
  }

  const hashed_password = await Bun.password.hash(password);

  const newUser: NewUser = {
    username: username,
    user_type: "user" as const,
    hashed_password: hashed_password,
    data: { ...user },
  };

  const success = await db.createUser(newUser);
  if (success.length < 0) {
    return c.json({ error: "Failed to create user" }, 500);
  }

  // Create session and auto login the user
  const info = getConnInfo(c);
  const ip_address = info.remote.address!;
  const [dbUser] = await db.getUserByUsername(username);
  const userAgent = c.req.header("User-Agent")!;
  if (!dbUser) {
    return c.json({ error: "User not found" }, 404);
  }
  const token = crypto.randomUUID();

  // Create session
  await db.createSession(token, dbUser.id, ip_address, userAgent);

  // Set cookie
  setCookie(c, "_Host-session", token, {
    maxAge: 60 * 60 * 24 * 7,
    httpOnly: true,
    secure: false,
    path: "/",
    sameSite: "lax",
  });

  return c.json({
    user: dbUser,
    token: token,
  });
});



// Login route
app.post("/login", async (c) => {
  const body = await c.req.json();

  const { username, password } = body;

  if (!username || !password) {
    return c.json({ error: "Missing required fields" }, 400);
  }

  const { hashed_password, ...user } = await db.getAuthUserByUsername(username);
  if (!user) {
    return c.json({ error: "Invalid credentials" }, 401);
  }

  const valid = await Bun.password.verify(password, hashed_password ?? "");
  if (!valid) {
    return c.json({ error: "Invalid credentials" }, 401);
  }

  const info = getConnInfo(c);
  const ip_address = info.remote.address!;
  const userAgent = c.req.header("User-Agent")!;
  const token = crypto.randomUUID();

  // Create session
  await db.createSession(token, user.id, ip_address, userAgent);

  // Set cookie
  setCookie(c, "_Host-session", token, {
    maxAge: 60 * 60 * 24 * 7,
    httpOnly: true,
    secure: false,
    path: "/",
    sameSite: "lax",
  });

  return c.json({
    user: user,
    token: token,
  });
});


// Guest
app.post("/guest", async (c) => {
  const body = await c.req.json();

  const { user } = body;

  if (!user) {
    return c.json({ error: "Missing required fields" }, 400);
  }


  const newUser: NewUser = {
    username: user.username,
    user_type: "guest" as const,
    data: { ...user },
  };

  const success = await db.createUser(newUser);
  if (success.length < 0) {
    return c.json({ error: "Failed to create user" }, 500);
  }

  // Create session and auto login the user
  const info = getConnInfo(c);
  const ip_address = info.remote.address!;
  const [dbUser] = await db.getUserByUsername(user.username);
  const userAgent = c.req.header("User-Agent")!;
  if (!dbUser) {
    return c.json({ error: "User not found" }, 404);
  }
  const token = crypto.randomUUID();

  // Create session
  await db.createSession(token, dbUser.id, ip_address, userAgent);

  // Set cookie
  setCookie(c, "_Host-session", token, {
    maxAge: 60 * 60 * 24 * 7,
    httpOnly: true,
    secure: false,
    path: "/",
    sameSite: "lax",
  });

  return c.json({
    user: dbUser,
    token: token,
  });

})


// Logout route
app.post("/logout", async (c) => {
  const cookie = getCookie(c, "_Host-session");
  if (!cookie) {
    return c.json({ error: "Missing Auth token" }, 401);
  }
  const user = await db.getSessionUser(cookie);
  const success = await db.revokeSession(cookie);
  if (!success) {
    throw new Error("Failed to Logout user");
  }

  deleteCookie(c, "_Host-session");

  // Remove user from db, if the user is a guest
  if (user.user_type === 'guest') {
    const removed = db.removeUser(user.id)
    if (!removed) {
      throw new Error("Error removing Guest user")
    }

  }
  return c.json({ message: "Logged out successfully" });
});



// me
app.get("/me", authMiddleware, async (c) => {
  const user = c.get("user");
  return c.json({ user });
});

export default app;
